# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wtyczka_projekt2_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wtyczka_projekt2DialogBase(object):
    def setupUi(self, wtyczka_projekt2DialogBase):
        wtyczka_projekt2DialogBase.setObjectName("wtyczka_projekt2DialogBase")
        wtyczka_projekt2DialogBase.resize(427, 317)
        self.button_box = QtWidgets.QDialogButtonBox(wtyczka_projekt2DialogBase)
        self.button_box.setGeometry(QtCore.QRect(40, 270, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.radioButton_przewyzszenia = QtWidgets.QRadioButton(wtyczka_projekt2DialogBase)
        self.radioButton_przewyzszenia.setGeometry(QtCore.QRect(140, 180, 141, 18))
        self.radioButton_przewyzszenia.setObjectName("radioButton_przewyzszenia")
        self.radioButton_pole = QtWidgets.QRadioButton(wtyczka_projekt2DialogBase)
        self.radioButton_pole.setGeometry(QtCore.QRect(140, 200, 141, 18))
        self.radioButton_pole.setObjectName("radioButton_pole")
        self.label = QtWidgets.QLabel(wtyczka_projekt2DialogBase)
        self.label.setGeometry(QtCore.QRect(140, 110, 181, 16))
        self.label.setObjectName("label")
        self.mMapLayerComboBox = QgsMapLayerComboBox(wtyczka_projekt2DialogBase)
        self.mMapLayerComboBox.setGeometry(QtCore.QRect(120, 140, 160, 27))
        self.mMapLayerComboBox.setObjectName("mMapLayerComboBox")

        self.retranslateUi(wtyczka_projekt2DialogBase)
        self.button_box.accepted.connect(wtyczka_projekt2DialogBase.accept) # type: ignore
        self.button_box.rejected.connect(wtyczka_projekt2DialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(wtyczka_projekt2DialogBase)

    def retranslateUi(self, wtyczka_projekt2DialogBase):
        _translate = QtCore.QCoreApplication.translate
        wtyczka_projekt2DialogBase.setWindowTitle(_translate("wtyczka_projekt2DialogBase", "wtyczka projekt 2"))
        self.radioButton_przewyzszenia.setText(_translate("wtyczka_projekt2DialogBase", "liczenie przewyższenia"))
        self.radioButton_pole.setText(_translate("wtyczka_projekt2DialogBase", "liczenia pola powierzchni"))
        self.label.setText(_translate("wtyczka_projekt2DialogBase", "wybierz aktywna warstwe"))
from qgsmaplayercombobox import QgsMapLayerComboBox


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wtyczka_projekt2DialogBase = QtWidgets.QDialog()
    ui = Ui_wtyczka_projekt2DialogBase()
    ui.setupUi(wtyczka_projekt2DialogBase)
    wtyczka_projekt2DialogBase.show()
    sys.exit(app.exec_())
